#Color Black GitHub
@accentColor = #0D1117

Button.selectedBackground=shade(@accentColor,15%)
Button.pressedBackground=shade(@accentColor,20%)
Button.disabledBackground=rgb(255,255,255)
Button.disabledText=rgb(0,0,0)

Component.arc = 10
TextComponent.arc = 10
Button.arc = 10

TextField.margin = 6,6,6,6
FormattedTextField.margin = 6,6,6,6
PasswordField.margin = 6,6,6,6
ComboBox.padding=6,6,6,6

ComboBox.disabledForeground = rgb(0,0,0)
ComboBox.disabledBackground = rgb(255,255,255)

TextField.inactiveBackground = rgb(255,255,255)

# Style untuk header tabel
TableHeader.height=30
TableHeader.hoverBackground=null
TableHeader.pressedBackground=null
TableHeader.separatorColor=rgb(206,206,206)

# Style untuk isi tabel
Table.rowHeight=30
Table.cellFocusColor=null
Table.selectionBackground=rgb(235,235,235)
Table.selectionInactiveBackground=rgb(255,255,255)
Table.selectionForeground=rgb(0,0,0)
Table.cellMargins=0,0,0,0
